name: VCCW - Vagrant based development environment for WordPress
markdown: redcarpet
highlighter: true
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
header:
    title: VCCW
    description: Vagrant based development environment for WordPress plugins, themes, or websites.
footer: Initial code by <a href="http://firegoby.jp/">Takayuki Miyauchi</a>.
scroll_to_top: <p class="scroll-to-top"><a href="#top"><i class="fa fa-arrow-up"></i> Back to top</a></p>
